[package]
name = "bigram1"
version = "0.1.0"
authors = ["Mashariq Khan <Mashariq.Khan@footlocker.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.7"
